context:
  version: '0.22.0'

package:
  name: _r-nmf
  version: ${{ version|replace("-", "_") }}

source:
  url:
    - ${{ cran_mirror }}/src/contrib/NMF_${{ version }}.tar.gz
    - ${{ cran_mirror }}/src/contrib/Archive/NMF/NMF_${{ version }}.tar.gz
  sha256: 989d024bdf5379130406d7f679f690fd5b228cf6f729584855364f1bfad0542c

build:
  noarch: generic
  number: 1000

requirements:
  ignore_run_exports:
    from_package:
      - r-base
  host:
    - r-base
  run:
    - r-base
    - bioconda::r-nmf ==${{ version }}

tests:
  - script:
      - $R -e "library('NMF')"

about:
  homepage: http://renozao.github.io/NMF
  license: GPL-2.0-or-later
  summary: Provides a framework to perform Non-negative Matrix Factorization (NMF). The package
    implements a set of already published algorithms and seeding methods, and provides
    a framework to test, develop and plug new/custom algorithms. Most of the built-in
    algorithms have been optimized in C++, and the main interface function provides
    an easy way of performing parallel computations on multicore machines.
  license_family: GPL3
  license_file: 
    # - ${{ env.get("PREFIX", default="NOT_A_PATH") }}/lib/R/share/licenses/GPL-2
    # - ${{ env.get("PREFIX", default="NOT_A_PATH") }}/lib/R/share/licenses/GPL-3
    - GPL-2-3

extra:
  recipe-maintainers:
    - conda-forge/r
